name: Grumpy engineer
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
#theme: jekyll-theme-architect
theme: minimal-mistakes-jekyll
skin: dark
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
