name: Grumpy engineer
title: Inside the head of a grumpy engineer
site.description: An engineer looking at the world with a critical eye.
url: "https://fenallen.github.io"
repositoery: "https://github.com/fenallen/fenallen.github.io"
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
minimal_mistakes_skin: "default"
plugins:
#  - jekyll-paginate
#  - jekyll-sitemap
#  - jekyll-gist
#  - jekyll-feed
#  - jemoji
  - jekyll-include-cache

include: ["_pages"]

# _config.yml (defaults)
#repository: "fenallen/fenallen.github.io"
#staticman:
#  endpoint: "http://localhost:8088/v2/entry/"
#  branch: "master"

#reCaptcha:
#  enabled: false

comments:
  provider: "disqus"
  disqus:
    shortname: "fenallen"
  #provider: "staticman_v2"


defaults:
# _pages
- scope:
    path: ""
    type: pages
  values:
    layout: single
    author_profile: true
# _posts
- scope:
    path: ""
    type: posts
  values:
    comments: true
    layout: single
    author_profile: true
    read_time: true
    share: true
    related: true
    toc: false

author:
  name     : "Allen"
  avatar   : "/assets/images/bio-photo.jpg"
  bio      : "An engineer looking at the world with a critical eye."
  location : "Oxfordshire, UK"
